// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgraqigwhurrtkgyllqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncmFxaWd3aHVycnRrZ3lsbHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDI4MzEsImV4cCI6MjA2MTY3ODgzMX0.baBHoxssEyZfFHc2vFUHHrTNksl3fhg5tft9CSgdbCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);